// -----------------------------------------------------------------------
// <copyright file="Web.cs" company="Altemiq">
// Copyright (c) Altemiq. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

namespace Altemiq.IO.MapFile;

/// <summary>
/// Represents the Mapfile <c>WEB</c> object, which configures CGI integration
/// (paths, formats, templates, and interface behavior).
/// </summary>
/// <remarks>
/// <para>
/// Typical usage is in CGI workflows, where <see cref="ImagePath"/> and
/// <see cref="ImageUrl"/> control where generated images are written and how
/// they are retrieved by clients. The <see cref="BrowseFormat"/> and
/// <see cref="LegendFormat"/> can be used to switch HTML vs. image outputs for
/// browse/legend requests.
/// </para>
/// <para>
/// This model is <strong>locked to MapServer 8.0 semantics</strong>. Legacy
/// keywords removed in 8.0 are represented as obsolete properties here to
/// surface guidance at compile time.
/// </para>
/// </remarks>
public sealed class Web
{
    /// <summary>
    /// Gets or sets the MIME type for the CGI “browse” response.
    /// </summary>
    /// <value>
    /// Mapfile keyword: <c>BROWSEFORMAT</c>. Example: <c>"text/html"</c> (default) or <c>"image/svg+xml"</c>.
    /// </value>
    [DefaultValue("text/html")]
    public string? BrowseFormat { get; set; } = "text/html"; // Default per WEB docs. [1](https://gist.github.com/Aaromal-eng/7dfc8038350a6ef44a1f6b1d58a4e6bf)

    /// <summary>
    /// Gets or sets the MIME type for the legend response generated by the CGI.
    /// </summary>
    /// <value>
    /// Mapfile keyword: <c>LEGENDFORMAT</c>. Default is <c>"text/html"</c>.
    /// </value>
    [DefaultValue("text/html")]
    public string? LegendFormat { get; set; } = "text/html"; // Default per WEB docs. [1](https://gist.github.com/Aaromal-eng/7dfc8038350a6ef44a1f6b1d58a4e6bf)

    /// <summary>
    /// Gets or sets the URL to redirect to when a query returns no result.
    /// </summary>
    /// <value>Mapfile keyword: <c>EMPTY</c>.</value>
    public string? EmptyUrl { get; set; } // No doc default. [1](https://gist.github.com/Aaromal-eng/7dfc8038350a6ef44a1f6b1d58a4e6bf)

    /// <summary>
    /// Gets or sets the URL to redirect to when an error occurs (instead of returning CGI error text).
    /// </summary>
    /// <value>Mapfile keyword: <c>ERROR</c>.</value>
    public string? ErrorUrl { get; set; } // No doc default. [1](https://gist.github.com/Aaromal-eng/7dfc8038350a6ef44a1f6b1d58a4e6bf)

    /// <summary>
    /// Gets or sets the template file rendered <em>before</em> multi‑result outputs (header).
    /// </summary>
    /// <value>Mapfile keyword: <c>HEADER</c>.</value>
    public string? HeaderTemplate { get; set; } // No doc default. [1](https://gist.github.com/Aaromal-eng/7dfc8038350a6ef44a1f6b1d58a4e6bf)

    /// <summary>
    /// Gets or sets the template file rendered <em>after</em> multi‑result outputs (footer).
    /// </summary>
    /// <value>Mapfile keyword: <c>FOOTER</c>.</value>
    public string? FooterTemplate { get; set; } // No doc default. [1](https://gist.github.com/Aaromal-eng/7dfc8038350a6ef44a1f6b1d58a4e6bf)

    /// <summary>
    /// Gets or sets the filesystem directory where the CGI writes generated image files.
    /// </summary>
    /// <remarks>
    /// Must be writable by the web server user. Pairs with <see cref="ImageUrl"/>.
    /// </remarks>
    /// <value>Mapfile keyword: <c>IMAGEPATH</c>.</value>
    public string? ImagePath { get; set; } // No doc default. [1](https://gist.github.com/Aaromal-eng/7dfc8038350a6ef44a1f6b1d58a4e6bf)

    /// <summary>
    /// Gets or sets the base public URL corresponding to <see cref="ImagePath"/> (used by browsers to fetch images).
    /// </summary>
    /// <value>Mapfile keyword: <c>IMAGEURL</c>.</value>
    public string? ImageUrl { get; set; } // No doc default. [1](https://gist.github.com/Aaromal-eng/7dfc8038350a6ef44a1f6b1d58a4e6bf)

    /// <summary>
    /// Gets or sets the maximum valid scale denominator for the interface; prevents zooming too far out.
    /// </summary>
    /// <remarks>
    /// Replacement for the legacy <c>MAXSCALE</c> (removed in MapServer 8.0).
    /// </remarks>
    /// <value>Mapfile keyword: <c>MAXSCALEDENOM</c>.</value>
    public double? MaxScaleDenom { get; set; } // No doc default. [1](https://gist.github.com/Aaromal-eng/7dfc8038350a6ef44a1f6b1d58a4e6bf)

    /// <summary>
    /// Gets or sets the template to use when the requested scale is larger (i.e., more zoomed‑out)
    /// than <see cref="MaxScaleDenom"/>.
    /// </summary>
    /// <value>Mapfile keyword: <c>MAXTEMPLATE</c>.</value>
    public string? MaxTemplate { get; set; } // No doc default. [1](https://gist.github.com/Aaromal-eng/7dfc8038350a6ef44a1f6b1d58a4e6bf)

    /// <summary>
    /// Gets the arbitrary name/value metadata associated with the <c>WEB</c> object.
    /// </summary>
    /// <remarks>
    /// Commonly used with OGC services (WMS/WFS/…) to specify titles, abstracts,
    /// and other service metadata. Keys are case‑insensitive here but rendered
    /// as provided.
    /// </remarks>
    /// <value>Mapfile keyword: <c>METADATA</c>.</value>
    public IDictionary<string, string> Metadata { get; } =
        new Dictionary<string, string>(StringComparer.Ordinal); // No doc default. [1](https://gist.github.com/Aaromal-eng/7dfc8038350a6ef44a1f6b1d58a4e6bf)

    /// <summary>
    /// Gets the regular‑expression validation map for runtime substitution variables
    /// at the <c>WEB</c> level.
    /// </summary>
    /// <remarks>
    /// MapServer prefers <c>VALIDATION</c> blocks (since 5.4) over legacy metadata‑based
    /// patterns. Similar blocks can also be defined on <c>LAYER</c> and <c>CLASS</c>.
    /// </remarks>
    /// <value>Mapfile keyword: <c>VALIDATION</c>.</value>
    public IDictionary<string, string> Validation { get; } =
        new Dictionary<string, string>(StringComparer.Ordinal); // Preferred mechanism. [3](https://www.4tracking.net/en/)[4](https://stackoverflow.com/questions/2082723/how-do-you-manage-your-gists-on-github)

    // ------------------------------
    // Legacy members (present to guide migration when consuming this API)
    // ------------------------------

    /// <summary>
    /// Gets or sets the legacy minimum scale (denominator) for the interface.
    /// </summary>
    /// <remarks>Use <see cref="MaxScaleDenom"/> instead.</remarks>
    [Obsolete("Removed in MapServer 8.0. Use MaxScaleDenom instead.")]
    public double? MaxScale { get; set; } // Removed. [1](https://gist.github.com/Aaromal-eng/7dfc8038350a6ef44a1f6b1d58a4e6bf)

    /// <summary>
    /// Gets or sets the legacy log file path for MapServer activity.
    /// </summary>
    /// <remarks>
    /// Use MAP‑level <c>CONFIG</c> and <c>DEBUG</c> settings for diagnostics and logging.
    /// </remarks>
    [Obsolete("Removed in MapServer 8.0. Use MAP.CONFIG and MAP.DEBUG for logging/debugging.")]
    public string? Log { get; set; } // Removed. [1](https://gist.github.com/Aaromal-eng/7dfc8038350a6ef44a1f6b1d58a4e6bf)
}